---
title: Christophe Ducamp
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: christophe@ducamp.me
description: "Un premier pas pour étudier la configuration d'un site statique avec l'appui de la communauté JamStatic. Apprendre à configurer un site personnel pour mes
  enfants et amis. Explorer les interfaces-utilisateur mobiles."
baseurl: 
url: https://christophe.ducamp.me
twitter_username: xtof_fr
github_username: ChristopheDucamp
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
